### ISSUE TITLE
Not able to receive push when app is closed on android devices

### ISSUE THREAD

**Issue by umeshk** [urbanairship/urbanairship-cordova#289]
# Please fill out this template when submitting an issue.
All lines beginning with an ℹ symbol indicate information that's important for you to provide to ensure your issue is resolved as quickly and efficiently as possible.

❗For how-to inquiries involving Urban Airship functionality or use cases, please
contact (support)[https://support.urbanairship.com/hc/en-us].

# Preliminary Info

### What version of urbanairship-cordova are you using?
ℹ Urban Airship 7.5.0.

### Is your issue affecting the Android platform, iOS platform, or both?
ℹ Android.

### What version of cordova-ios and/or cordova-android are you using?
ℹ Urban Airship 7.5.0..

### What are the versions of any relevant development tools you are using?
ℹ If applicable, please include any other relevant information about the version of your
IDE, plugin(s), or package manager(s) here.

# Report

### What unexpected behavior are you seeing?
ℹ Please provide a brief description of the unexpected behavior here.
We are not receiving the push when app is closed (not running in background) on android devices

### What is the expected behavior?
ℹ Please provide a brief description of the expected behavior here.
We should able to receive push because it was working fine for 7.3.1 version of Urban Airship plugin

### What are the steps to reproduce the unexpected behavior?
ℹ Please provide reproduction steps here.

### Do you have logging for the issue?
ℹ Please provide links to gists of any pertinent logs here.

**Comment by rlepinski** [comment]
What do you mean by push? Notifications or event listeners? How are you backgrounding the app? Could you give detailed reproduction steps?

**Comment by umeshk** [comment]
Push means notifications. Backgrounding app means we are explicitly closing
it which means it is not running in background.
Reproduction steps are just send push notification when app is in above
state for Android devices. You will not receive it at all where as in case
of app running in background or foreground we do get push notification.

**Comment by rlepinski** [comment]
@umeshk How are you explicitly closing it? What device? What Android version?

**Comment by rlepinski** [comment]
@umeshk I am unable to reproduce. 

If you are closing the app using a 3rd party tool or force stopping the app in the app settings screen it prevents apps from using any intents (including push) until the app is started again. If you are just swiping away in the last used screen it should be fine. However a few devices have a whitelist of apps that can run in the background and those devices prevent push from working unless the app is foregrounded.

**Comment by umeshk** [comment]
Yes we are swiping away in the last used screen. But UA plugin 7.3.1 did
not have this issue on the same device i.e. for android nugat, orio and pie
versions

**Comment by umeshk** [comment]
@rlepinski did you get a chance to look at issue I have posted above?

**Comment by rlepinski** [comment]
@umeshk I am unable to reproduce. I tied with 7.5.1 but either version should be fine. Could you provide a sample projext that shows that behavior?

**Comment by umeshk** [comment]
@rlepinski we are using 7.5.0. Is it something its fixed in 7.5.1?

**Comment by rlepinski** [comment]
There is an issue where if you receive a push when push is disabled it will crash. Nothing around notifications handling in the background has changed in the plugin. Please try 7.5.1, if that still does not work provide a sample project that reproduces the issue

**Comment by umeshk** [comment]
@rlepinski thanks for information. We are looking into by implementing latest plugin.

**Comment by shreyasb0912** [comment]
@rlepinski We tried using the latest version of the plugin i.e 7.5.1 but we are still facing the same issue. Notification are not received at all when the app is remove from background stack. Just to bring to your notice that we had not been facing this issue in versions prior to 7.5.0.

**Comment by rlepinski** [comment]
@shreyasb0912 are you working on the same project as @umeshk ?

I still do not have enough information to reproduce the issue. Could please provide:
- Verbose logs when a push is received in the background
- What devices you are seeing this issue on
- If you tried other devices
- How you are calling takeOff (in js or config file)
- A sample project showing this issue

Again I am able to receive notifications in the BG fine on 7.5.1.

**Comment by umeshk** [comment]
@rlepinski yes @umeshk  and @shreyasb0912 we are in same team. 
You are saying that **Again I am able to receive notifications in the BG fine on 7.5.1.** so was app running in background or it was removed from background stack?

I will ask @shreyasb0912 to provide necessary logs.

**Comment by rlepinski** [comment]
Can I also get your cordova version, platform version, etc... ?

My setup:
```
$ cordova plugins
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-whitelist 1.3.3 "Whitelist"
urbanairship-cordova 7.5.1 "Urban Airship"
$ cordova --version
8.1.2 (cordova-lib@8.1.1)
$ cordova platform
Installed platforms:
  android 7.1.4
Available platforms: 
  browser ~5.0.1
  ios ~4.5.4
  osx ~4.0.1
  windows ~6.0.0
```

I tested both types of takeOff - configuring it config.xml and calling takeOff from JS. Here is a video of my device receiving a push in the background:

[device-2019-02-21-093150.mp4.zip](https://github.com/urbanairship/urbanairship-cordova/files/2890381/device-2019-02-21-093150.mp4.zip)

**Comment by rlepinski** [comment]
@umeshk I can receive push if the device is in the background (just minimized the app), or if i swipe it away in the recent screens view

**Comment by umeshk** [comment]
@rlepinski thanks for the video. I saw it you receive push in any case. You mentioned that you did changes in config.xml and in JS as well. So do we need to do changes for this scenario?

**Comment by rlepinski** [comment]
@umeshk No you should be fine. We added the ability to configure the plugin through JS instead of the config.xml file. I tested both approaches and everything seems to be working. The video is when I configured the plugin through the config.xml file.

**Comment by umeshk** [comment]
@rlepinski 

We are using Outsystems to build our mobile app. So here is the the plugin information. If we change last line i.e. UA plugin from 7.5 to 7.3 then it works in any case.

  "cordova-plugin-network-information": "2.0.1",
  "com.outsystems.plugins.broadcaster": "1.0.4",
  "com.outsystems.plugins.ossecurity": "1.2.3",
  "com.outsystems.plugins.applicationinfo": "1.0.2",
  "com.outsystems.plugins.logger": "1.2.4-1",
  "com.outsystems.plugins.crashhandler": "1.0.2",
  "cordova-plugin-whitelist": "1.3.3",
  "cordova-plugin-device": "1.1.3",
  "cordova-plugin-splashscreen": "5.0.2",
  "com.outsystems.plugins.filechooser": "1.0.1",
  "cordova-plugin-statusbar": "2.4.2-OS1",
  "cordova-sqlite-storage": "1.4.5-OS4",
  "com.outsystems.plugins.osdbupgrader": "1.1.4",
  "com.outsystems.plugins.oscache": "2.4.4",
  "com.outsystems.plugins.manifest": "1.1.1",
  "com.outsystems.plugins.prebundle": "1.5.2",
  "com.outsystems.plugins.loader": "1.10.4",
  "com.outsystems.plugins.deeplinks": "1.1.1",
  "urbanairship-cordova": "7.5.0"
  
  **"urbanairship-cordova": "7.3.0"**

**Comment by rlepinski** [comment]
@umeshk I am going to need some logs. I am not that familiar with outsystems nor will it be easy for me to use that framework.

Could you try using `7.3.1` & `7.3.2` to see if they have the same issues?

**Comment by umeshk** [comment]
@rlepinski issue is solved now. We have updated the build-extras.gradle to use below line
implementation 'com.urbanairship.android:urbanairship-fcm:9.5.6'
instead of 
implementation 'com.urbanairship.android:urbanairship-fcm:9.7.0'
and it worked fine

**Comment by crow** [comment]
@umeshk thanks for the update

**Comment by rlepinski** [comment]
@umeshk Not sure why 9.7.0 would break your background push. https://github.com/urbanairship/android-library/compare/9.5.6...9.7.0 
The main differences are targeting and compiling against Android P.
